/**
 * IsleMap Radar Config (.imx) — overlay visual design pack.
 * Magic IMX1 + base64(UTF-8 JSON). Does not include location, hotkeys, waypoints, etc.
 */

const RADAR_CONFIG_KIND = "islemap-radar-config";
const RADAR_CONFIG_VERSION = 1;
const IMX_MAGIC = Buffer.from("IMX1", "ascii");

/** Keys shared via Radar Config export/import (overlay look only). */
const RADAR_CONFIG_KEYS = Object.freeze([
  "mapSize",
  "mapOpacity",
  "mapDesign",
  "basemap",
  "windowOpacity",
  "overlayOpacity",
  "position",
  "overlayDisplay",
  "zoom",
  "followPlayer",
  "borderColor",
  "borderWidth",
  "borderGlow",
  "borderStyle",
  "borderEffect",
  "borderEffectCount",
  "borderEffectSpeed",
  "borderEffectIntensity",
  "borderEffectSize",
  "borderEffectDistance",
  "borderEffectDinoSpecies",
  "borderEffectOrientation",
  "borderEffectColor",
  "borderEffectRandomGradient",
  "borderEffectRandomSpawn",
  "borderEffectSound",
  "borderEffectSoundVolume",
  "borderEffectBeatSensitivity",
  "borderEffectBeatPunch",
  "borderEffectBeatSmooth",
  "borderEffectBeatBass",
  "borderEffectBeatMotion",
  "borderEffectBeatRings",
  "borderEffectBeatStyle",
  "borderEffectBeatBarSize",
  "borderEffectBeatBarLength",
  "borderEffectBeatBarDistance",
  "borderEffectBeatBarSpacing",
  "borderEffectBeatBarRotation",
  "borderEffectBeatLegendGradient",
  "frameScale",
  "frameOffsetX",
  "frameOffsetY",
  "frameHoleX",
  "frameHoleY",
  "frameMapScale",
  "framePad",
  "frameMapOnTop",
  "pinColor",
  "fovColor",
  "fovStyle",
  "fovAngle",
  "fovLength",
  "fovIntensity",
  "fovPulse",
  "playerIconStyle",
  "playerIconDinoSpecies",
  "playerIcon3dSize",
  "playerIcon3dSpeed",
  "playerIcon3dGlow",
  "playerIcon3dAnimate",
  "playerIcon3dOrientation",
  "playerIconFollowHeading",
  "playerIconCustomData",
  "playerIconCustomName",
  "showFov",
  "showCompass",
  "showChrome",
  "showRadarSweep",
  "radarSweepStyle",
  "radarSweepDirection",
  "radarSweepSeconds",
]);

function pickRadarSettings(source = {}) {
  const out = {};
  if (!source || typeof source !== "object") return out;
  for (const key of RADAR_CONFIG_KEYS) {
    if (Object.prototype.hasOwnProperty.call(source, key)) {
      out[key] = source[key];
    }
  }
  return out;
}

/**
 * @param {object} settings full or partial settings
 * @param {{ name?: string }} [meta]
 * @returns {Buffer}
 */
function buildImxBuffer(settings, meta = {}) {
  const name = String(meta.name || "Radar Config")
    .trim()
    .slice(0, 80) || "Radar Config";
  const payload = {
    version: RADAR_CONFIG_VERSION,
    kind: RADAR_CONFIG_KIND,
    name,
    exportedAt: new Date().toISOString(),
    settings: pickRadarSettings(settings),
  };
  const b64 = Buffer.from(JSON.stringify(payload), "utf8").toString("base64");
  return Buffer.concat([IMX_MAGIC, Buffer.from(b64, "utf8")]);
}

/**
 * @param {Buffer|Uint8Array|string} input
 * @returns {{ ok: true, payload: object } | { ok: false, reason: string }}
 */
function parseImxBuffer(input) {
  let buf;
  try {
    if (Buffer.isBuffer(input)) buf = input;
    else if (input instanceof Uint8Array) buf = Buffer.from(input);
    else if (typeof input === "string") buf = Buffer.from(input, "binary");
    else return { ok: false, reason: "bad-input" };
  } catch {
    return { ok: false, reason: "bad-input" };
  }

  if (buf.length < 5) return { ok: false, reason: "bad-magic" };
  if (buf.subarray(0, 4).toString("ascii") !== "IMX1") {
    return { ok: false, reason: "bad-magic" };
  }

  let json;
  try {
    const b64 = buf.subarray(4).toString("utf8").replace(/\s+/g, "");
    json = JSON.parse(Buffer.from(b64, "base64").toString("utf8"));
  } catch {
    return { ok: false, reason: "bad-payload" };
  }

  if (
    !json ||
    typeof json !== "object" ||
    json.kind !== RADAR_CONFIG_KIND ||
    Number(json.version) !== RADAR_CONFIG_VERSION
  ) {
    return { ok: false, reason: "bad-schema" };
  }
  if (!json.settings || typeof json.settings !== "object") {
    return { ok: false, reason: "bad-settings" };
  }

  const name =
    String(json.name || "Radar Config")
      .trim()
      .slice(0, 80) || "Radar Config";

  return {
    ok: true,
    payload: {
      version: RADAR_CONFIG_VERSION,
      kind: RADAR_CONFIG_KIND,
      name,
      exportedAt: json.exportedAt ? String(json.exportedAt) : null,
      settings: pickRadarSettings(json.settings),
    },
  };
}

/**
 * Merge radar keys from pack into current settings object (does not write disk).
 * @returns {object} partial suitable for saveSettings / applySettings
 */
function applyRadarSettings(_current, packSettings) {
  return pickRadarSettings(packSettings || {});
}

function isImxPath(filePath) {
  return (
    typeof filePath === "string" &&
    filePath.length > 4 &&
    filePath.toLowerCase().endsWith(".imx")
  );
}

/** Built-in overlay looks — preview/apply like an imported .imx pack. */
const FRAME_ALIGN = Object.freeze({
  frameScale: 1.49,
  frameOffsetX: 0,
  frameOffsetY: 0,
  frameHoleX: 50,
  frameHoleY: 47.36,
  frameMapScale: 1.04,
  framePad: 0.26,
  frameMapOnTop: false,
});

function tpl(id, name, description, settings) {
  return Object.freeze({
    id,
    name,
    description,
    settings: Object.freeze({ ...settings }),
  });
}

const RADAR_TEMPLATES = Object.freeze([
  tpl("audio-beat", "Audio Beat", "Default look — tactical map with audio-reactive beat rim", {
    mapDesign: "tactical",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#5ec8ff",
    borderWidth: 3,
    borderGlow: 14,
    borderEffect: "beat",
    borderEffectBeatStyle: "scanline",
    borderEffectColor: "#5ec8ff",
    borderEffectSound: true,
    pinColor: "#5ef0ff",
    fovColor: "#b6ff4a",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("classic-islemap", "Classic IsleMap", "Clean tactical cyan ring without beat FX", {
    mapDesign: "tactical",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#5ec8ff",
    borderWidth: 3,
    borderGlow: 14,
    borderEffect: "none",
    pinColor: "#5ef0ff",
    fovColor: "#b6ff4a",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("night-ops", "Night Ops", "Night blue grade, thin cyan ring, pulse", {
    mapDesign: "night",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#4aa8ff",
    borderWidth: 2,
    borderGlow: 18,
    borderEffect: "pulse",
    borderEffectColor: "#4aa8ff",
    borderEffectIntensity: 0.9,
    borderEffectSpeed: 1.1,
    pinColor: "#7ec8ff",
    fovColor: "#5ef0ff",
    fovStyle: "beam",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "thin",
    radarSweepDirection: "cw",
    radarSweepSeconds: 5,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "carnotaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("phosphor-hunt", "Phosphor Hunt", "Green phosphor map with toxic rim FX", {
    mapDesign: "phosphor",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#3dff6a",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "toxic",
    borderEffectColor: "#3dff6a",
    borderEffectCount: 12,
    borderEffectIntensity: 1,
    pinColor: "#7dff9a",
    fovColor: "#b6ff4a",
    fovStyle: "soft",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "dilophosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("thermal-fire", "Thermal Fire", "Thermal grade with fire rim", {
    mapDesign: "thermal",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#ff6a2a",
    borderWidth: 3,
    borderGlow: 20,
    borderEffect: "fire",
    borderEffectColor: "#ff6a2a",
    borderEffectCount: 14,
    borderEffectSpeed: 1.2,
    borderEffectIntensity: 1,
    pinColor: "#ffd36a",
    fovColor: "#ff9a4a",
    fovStyle: "classic",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "tyrannosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("arctic-frost", "Arctic Frost", "Cold white-blue map with frost rim", {
    mapDesign: "arctic",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#c8e8ff",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "frost",
    borderEffectColor: "#a8d8ff",
    borderEffectCount: 10,
    borderEffectIntensity: 0.95,
    pinColor: "#e8f6ff",
    fovColor: "#9ad4ff",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("primal-frame", "Primal Frame", "Primal Pinas photo border, amber look", {
    mapDesign: "amber",
    basemap: "gateway-realistic",
    borderStyle: "primal-pinas",
    borderColor: "#e0a040",
    borderWidth: 3,
    borderGlow: 10,
    borderEffect: "orbit",
    borderEffectColor: "#e0a040",
    borderEffectCount: 8,
    ...FRAME_ALIGN,
    pinColor: "#ffd27a",
    fovColor: "#ffe08a",
    fovStyle: "soft",
    showFov: true,
    showCompass: false,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("isle-evrima", "Isle Evrima", "Evrima photo border with verdant grade", {
    mapDesign: "verdant",
    basemap: "gateway-realistic",
    borderStyle: "isle-evrima",
    borderColor: "#6ec86a",
    borderWidth: 3,
    borderGlow: 10,
    borderEffect: "dino",
    borderEffectColor: "#6ec86a",
    borderEffectCount: 6,
    borderEffectDinoSpecies: "triceratops",
    ...FRAME_ALIGN,
    pinColor: "#8ef08a",
    fovColor: "#b6ff4a",
    fovStyle: "los",
    showFov: true,
    showCompass: false,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("noir-sweep", "Noir Sweep", "High-contrast noir with classic radar sweep", {
    mapDesign: "noir",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#eeeeee",
    borderWidth: 2,
    borderGlow: 8,
    borderEffect: "none",
    pinColor: "#ffffff",
    fovColor: "#cccccc",
    fovStyle: "beam",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "classic",
    radarSweepDirection: "ccw",
    radarSweepSeconds: 4,
    playerIconStyle: "dot",
  }),
  tpl("satellite-clean", "Satellite Clean", "True-color satellite with soft orbit dots", {
    mapDesign: "satellite",
    basemap: "gateway-realistic",
    borderStyle: "classic",
    borderColor: "#8ec8ff",
    borderWidth: 2,
    borderGlow: 10,
    borderEffect: "orbit",
    borderEffectColor: "#8ec8ff",
    borderEffectCount: 10,
    pinColor: "#ffffff",
    fovColor: "#b6ff4a",
    fovStyle: "soft",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("topo-scout", "Topo Scout", "Chart-style topo with spark rim", {
    mapDesign: "topo",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#d4b896",
    borderWidth: 3,
    borderGlow: 12,
    borderEffect: "spark",
    borderEffectColor: "#e8c87a",
    borderEffectCount: 14,
    pinColor: "#ffe0a0",
    fovColor: "#c8e070",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("amber-dusk", "Amber Dusk", "Warm amber grade with smoke plumes", {
    mapDesign: "amber",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#e09040",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "smoke",
    borderEffectColor: "#c87830",
    borderEffectCount: 10,
    pinColor: "#ffc878",
    fovColor: "#ffb060",
    fovStyle: "classic",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "carnotaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("plasma-ring", "Plasma Ring", "Night map with plasma rim energy", {
    mapDesign: "night",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#b06aff",
    borderWidth: 3,
    borderGlow: 22,
    borderEffect: "plasma",
    borderEffectColor: "#c080ff",
    borderEffectCount: 12,
    borderEffectIntensity: 1,
    pinColor: "#e0a0ff",
    fovColor: "#80e0ff",
    fovStyle: "beam",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "dilophosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("lightning-storm", "Lightning Storm", "Noir skyline with lightning bolts", {
    mapDesign: "noir",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#a0d8ff",
    borderWidth: 2,
    borderGlow: 24,
    borderEffect: "lightning",
    borderEffectColor: "#d0f0ff",
    borderEffectCount: 8,
    pinColor: "#ffffff",
    fovColor: "#a0e0ff",
    fovStyle: "beam",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
  }),
  tpl("dragon-run", "Dragon Run", "Thermal hunt with 3D dragon rim runners", {
    mapDesign: "thermal",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#ff5030",
    borderWidth: 3,
    borderGlow: 18,
    borderEffect: "dragon",
    borderEffectColor: "#ff7040",
    borderEffectCount: 6,
    borderEffectDistance: 8,
    pinColor: "#ffd060",
    fovColor: "#ff9040",
    fovStyle: "classic",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "tyrannosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("dino-parade", "Dino Parade", "Verdant map with 3D dinosaur rim run", {
    mapDesign: "verdant",
    basemap: "gateway-realistic",
    borderStyle: "classic",
    borderColor: "#5ad060",
    borderWidth: 3,
    borderGlow: 14,
    borderEffect: "dinosaur",
    borderEffectColor: "#70e070",
    borderEffectCount: 5,
    borderEffectDinoSpecies: "triceratops",
    borderEffectDistance: 6,
    pinColor: "#a0ff90",
    fovColor: "#c0ff70",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("beat-rings", "Beat Rings", "Tactical audio-beat with expanding rings", {
    mapDesign: "tactical",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#5ef0c8",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "beat",
    borderEffectBeatStyle: "rings",
    borderEffectColor: "#5ef0c8",
    borderEffectBeatLegendGradient: true,
    pinColor: "#80ffe0",
    fovColor: "#b6ff4a",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("dual-sweep", "Dual Sweep", "Night ops with dual rotating sweeps", {
    mapDesign: "night",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#60b0ff",
    borderWidth: 2,
    borderGlow: 14,
    borderEffect: "none",
    pinColor: "#90d0ff",
    fovColor: "#70ffd0",
    fovStyle: "beam",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "dual",
    radarSweepDirection: "ccw",
    radarSweepSeconds: 3.5,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "carnotaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("glow-sweep", "Glow Sweep", "Phosphor map with glowing sweep arm", {
    mapDesign: "phosphor",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#40ff80",
    borderWidth: 2,
    borderGlow: 20,
    borderEffect: "none",
    pinColor: "#90ffb0",
    fovColor: "#c0ff60",
    fovStyle: "soft",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "glow",
    radarSweepDirection: "cw",
    radarSweepSeconds: 4.5,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "dilophosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("pulse-sweep", "Pulse Sweep", "Arctic frost rim plus pulse sweep", {
    mapDesign: "arctic",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#d0ecff",
    borderWidth: 2,
    borderGlow: 18,
    borderEffect: "pulse",
    borderEffectColor: "#b8e0ff",
    pinColor: "#f0f8ff",
    fovColor: "#a0d8ff",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "pulse",
    radarSweepDirection: "ccw",
    radarSweepSeconds: 5,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("chrome-hud", "Chrome HUD", "Tactical chrome labels with thin sweep", {
    mapDesign: "tactical",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#76b900",
    borderWidth: 2,
    borderGlow: 10,
    borderEffect: "orbit",
    borderEffectColor: "#76b900",
    borderEffectCount: 8,
    pinColor: "#b6ff4a",
    fovColor: "#5ef0ff",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: true,
    showRadarSweep: true,
    radarSweepStyle: "thin",
    radarSweepDirection: "cw",
    radarSweepSeconds: 6,
    playerIconStyle: "dot",
  }),
  tpl("beam-hunter", "Beam Hunter", "Satellite map with long FOV beam", {
    mapDesign: "satellite",
    basemap: "gateway-realistic",
    borderStyle: "classic",
    borderColor: "#ff9060",
    borderWidth: 3,
    borderGlow: 12,
    borderEffect: "spark",
    borderEffectColor: "#ffb080",
    borderEffectCount: 10,
    pinColor: "#ffe0c0",
    fovColor: "#ffd080",
    fovStyle: "beam",
    fovAngle: 40,
    fovLength: 1.6,
    fovIntensity: 0.8,
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "carnotaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("soft-grove", "Soft Grove", "Verdant soft FOV with gentle pulse", {
    mapDesign: "verdant",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#70c878",
    borderWidth: 3,
    borderGlow: 14,
    borderEffect: "pulse",
    borderEffectColor: "#80d888",
    borderEffectSpeed: 0.8,
    pinColor: "#a8f0a0",
    fovColor: "#c8ff90",
    fovStyle: "soft",
    fovIntensity: 0.55,
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("primal-night", "Primal Night", "Primal frame over night grade", {
    mapDesign: "night",
    basemap: "gateway-realistic",
    borderStyle: "primal-pinas",
    borderColor: "#6080c0",
    borderWidth: 3,
    borderGlow: 10,
    borderEffect: "frost",
    borderEffectColor: "#80a0e0",
    borderEffectCount: 8,
    ...FRAME_ALIGN,
    pinColor: "#a0c8ff",
    fovColor: "#70e0ff",
    fovStyle: "soft",
    showFov: true,
    showCompass: false,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "dilophosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("evrima-amber", "Evrima Amber", "Evrima frame with amber dusk grade", {
    mapDesign: "amber",
    basemap: "gateway-realistic",
    borderStyle: "isle-evrima",
    borderColor: "#d09040",
    borderWidth: 3,
    borderGlow: 10,
    borderEffect: "fire",
    borderEffectColor: "#e0a050",
    borderEffectCount: 8,
    ...FRAME_ALIGN,
    pinColor: "#ffd090",
    fovColor: "#ffc070",
    fovStyle: "classic",
    showFov: true,
    showCompass: false,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "tyrannosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("toxic-sweep", "Toxic Sweep", "Phosphor toxic rim plus glow sweep", {
    mapDesign: "phosphor",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#50ff60",
    borderWidth: 3,
    borderGlow: 18,
    borderEffect: "toxic",
    borderEffectColor: "#60ff70",
    borderEffectCount: 14,
    pinColor: "#a0ff90",
    fovColor: "#d0ff50",
    fovStyle: "soft",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "glow",
    radarSweepDirection: "ccw",
    radarSweepSeconds: 3.8,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "dilophosaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("orbit-gold", "Orbit Gold", "Amber gold with orbiting rim dots", {
    mapDesign: "amber",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#f0c040",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "orbit",
    borderEffectColor: "#ffd060",
    borderEffectCount: 12,
    pinColor: "#ffe080",
    fovColor: "#ffc050",
    fovStyle: "classic",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
  tpl("smoke-signal", "Smoke Signal", "Tactical dark with smoke rim FX", {
    mapDesign: "tactical",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#909090",
    borderWidth: 3,
    borderGlow: 12,
    borderEffect: "smoke",
    borderEffectColor: "#a8a8a8",
    borderEffectCount: 12,
    pinColor: "#5ef0ff",
    fovColor: "#b6ff4a",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: false,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "carnotaurus",
    playerIcon3dOrientation: "top",
  }),
  tpl("frost-sweep", "Frost Sweep", "Arctic frost rim with classic sweep", {
    mapDesign: "arctic",
    basemap: "gateway-official",
    borderStyle: "classic",
    borderColor: "#b8dcff",
    borderWidth: 3,
    borderGlow: 16,
    borderEffect: "frost",
    borderEffectColor: "#d0ecff",
    borderEffectCount: 12,
    pinColor: "#f0f8ff",
    fovColor: "#90c8ff",
    fovStyle: "los",
    showFov: true,
    showCompass: true,
    showChrome: false,
    showRadarSweep: true,
    radarSweepStyle: "classic",
    radarSweepDirection: "cw",
    radarSweepSeconds: 4.2,
    playerIconStyle: "dot",
    playerIconDinoSpecies: "triceratops",
    playerIcon3dOrientation: "top",
  }),
]);

function templatePreview(settings = {}) {
  return {
    design: settings.mapDesign || "tactical",
    basemap: settings.basemap || "gateway-official",
    borderStyle: settings.borderStyle || "classic",
    borderColor: settings.borderColor || "#5ec8ff",
    borderGlow: Number(settings.borderGlow ?? 14),
    pinColor: settings.pinColor || "#5ef0ff",
    fovColor: settings.fovColor || "#b6ff4a",
    effect: settings.borderEffect || "none",
    sweep: Boolean(settings.showRadarSweep),
  };
}

function listRadarTemplates() {
  return RADAR_TEMPLATES.map((t) => ({
    id: t.id,
    name: t.name,
    description: t.description || "",
    preview: templatePreview(t.settings),
  }));
}

function getRadarTemplate(id) {
  const t = RADAR_TEMPLATES.find((x) => x.id === id);
  if (!t) return null;
  return {
    version: RADAR_CONFIG_VERSION,
    kind: RADAR_CONFIG_KIND,
    name: t.name,
    exportedAt: null,
    templateId: t.id,
    settings: pickRadarSettings(t.settings),
  };
}

module.exports = {
  RADAR_CONFIG_KIND,
  RADAR_CONFIG_VERSION,
  RADAR_CONFIG_KEYS,
  RADAR_TEMPLATES,
  pickRadarSettings,
  buildImxBuffer,
  parseImxBuffer,
  applyRadarSettings,
  isImxPath,
  listRadarTemplates,
  getRadarTemplate,
};
